// Hooks barrel file
export { wizardReducer, createInitialWizardState } from './useWizardReducer';
export { WizardProvider, useWizard } from './WizardContext';
export type { WizardContextValue, WizardProviderProps } from './WizardContext';
export { useWizardNavigation } from './useWizardNavigation';
export type { UseWizardNavigationReturn } from './useWizardNavigation';
export { useSessionPersistence } from './useSessionPersistence';
export { usePrimaCalculation } from './usePrimaCalculation';
export type { UsePrimaCalculationReturn } from './usePrimaCalculation';
export { useBMICalculation } from './useBMICalculation';
export { useCoverages } from './useCoverages';
export type { UseCoveragesReturn } from './useCoverages';
export { useValidation } from './useValidation';
export type { UseValidationReturn } from './useValidation';
export { useQuoteSession } from './useQuoteSession';
export type { UseQuoteSessionReturn } from './useQuoteSession';
export { useCurrencyMask } from './useCurrencyMask';
export type { UseCurrencyMaskReturn } from './useCurrencyMask';
export { useAgeValidation } from './useAgeValidation';
export type { UseAgeValidationReturn } from './useAgeValidation';
export { useExtraprima } from './useExtraprima';
export type { UseExtraprimaReturn } from './useExtraprima';
